<a href="https://colab.research.google.com/github/zerryberry/C1/blob/master/NPVTAKEHOMEDAY01_(Questions)_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TAKE HOME LAB EXERCISE - 01

-----------

**(1).Create a 1D array with 10 values in it and then convert the 1D array to 2D array ?**

In [ ]:
import numpy as np
a= np.arange(10,20)
b= a.reshape((2,5))
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
b.ndim

2

-------------------------------------------------------------

**(2).Print or show only 3 decimal places of the numpy array `random_arr`**

In [ ]:
a= np.random.rand(10)
b= np.array(list(map(lambda x: round(x, 3), a)))

In [ ]:
b

array([0.102, 0.105, 0.197, 0.023, 0.684, 0.627, 0.784, 0.173, 0.373,
       0.768])

----------------------------------

**(3).The number of items printed to be limit in python numpy array a to a maximum of 6 elements.**

   
     Intake : x = np.arange(15)
               array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
               
     Result : ([ 0,  1,  2, ..., 12, 13, 14])

In [ ]:
np.set_printoptions(threshold = 6)
np.arange(15)

array([ 0,  1,  2, ..., 12, 13, 14])

---------------------

**(4). Take two arrays  `x` and `y` and Stack the `x` and `y` arrays Horizontal.**


    Intake:
                x = np.arange(10).reshape(2,-1)

                y = np.repeat(1, 10).reshape(2,-1)

 
    
    Result:       ([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
                   [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
x = np.arange(10).reshape(2,-1)
y = np.repeat(1, 10).reshape(2,-1)
np.stack((x,y),1).reshape((2,10))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

----------------------

**(5). Consider the given array's and print the values which are common in both the arrays.**
    
    
    Intake: 
   
        x = np.array([1,2,3,2,3,4,3,4,5,6])
        y = np.array([7,2,10,2,7,4,9,4,9,8])
 
    Results:
        
         ([2, 4])
            
    

In [ ]:
x = np.array([1,2,3,2,3,4,3,4,5,6])
y = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(x,y)

array([2, 4])

---------------------

**(6). There are two array x and y ,drop the items in `X` which already exist in `Y`.**

   
    INTAKE:
     x = np.array([1,2,3,4,5])
     y = np.array([5,6,7,8,9])
    
    
    RESULT:
     ([1,2,3,4])
        
    

In [ ]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
np.delete(x, np.where(x==np.intersect1d(x,y)))

array([1, 2, 3, 4])

--------------------------

**(7). Reverse the rows of a 2D array.**


    Intake : X = np.arange(9).reshape(3,3)
    
    Result :      ([[6, 7, 8],
                    [3, 4, 5],
                    [0, 1, 2]])

In [ ]:
x = np.arange(9).reshape(3,3)
x[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

----------------------

**(8). Reverse the columns of a 2D array.**

    Intake : X = np.arange(9).reshape(3,3)
    
    Result :     ([[2, 1, 0],
                   [5, 4, 3],
                   [8, 7, 6]])


In [ ]:
x = np.arange(9).reshape(3,3)
x[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

---------------------

**(9). Print the ranks for the given numeric array `x`.**
 
   
    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=10)
    print(x)
    [ 9  4 15  0 17 16 17  8  9  0]
    
    
    Result:
    [4 2 6 0 8 7 9 3 5 1]
    

In [ ]:
import numpy as np
np.random.seed(10)
x = np.random.randint(20, size=10)
x

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [ ]:
v= x.argsort().argsort()
v

array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1])

--------------------

**(10). For the given numeric array print the rank array with same shape of numeric array.**


    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=[2,5])
    print(a)
    [[ 9  4 15  0 17]
    [16 17  8  9  0]]
    
    Result:
    [[4 2 6 0 8]
    [7 9 3 5 1]]

In [ ]:
np.random.seed(10)
x = np.random.randint(20, size=[2,5])
print(x)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [ ]:
c= x.flatten().argsort().argsort().reshape((2,5))
c

array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]])

--------------------------------

**(11). Subtract the 1d array y_1d from the 2d array x_2d, such that each item of y_1d subtracts from respective row of x_2d.**
    
    Intake:
    x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
    y_1d = np.array([1,2,3])
    
    Result:
     [[2 2 2]
     [2 2 2]
     [2 2 2]]

In [ ]:
import numpy as np
x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
y_1d = np.array([1,2,3])

In [ ]:
a= y_1d.reshape((3,1))

In [ ]:
x_2d-a

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

----------------

# ----------------------------------HAPPY LEARNING--------------------------------------------------

-------------------